"""pgprovision: generate, apply and check SQL for the PostgREST test database."""

from pathlib import Path

import typer

import psycopg

from provision import checker, config, db, models, show, sqlgen

app = typer.Typer(
    name="pgprovision",
    help="Generate SQL from yaml templates, apply it to the database, and check the result.",
    no_args_is_help=True,
)
create_app = typer.Typer(help="Generate SQL files from the yaml templates.", no_args_is_help=True)
apply_app = typer.Typer(help="Run generated SQL files against the database.", no_args_is_help=True)
check_app = typer.Typer(help="Compare the live database against the yaml definitions.", no_args_is_help=True)
teardown_app = typer.Typer(help="Drop the objects defined in the yaml templates.", no_args_is_help=True)
show_app = typer.Typer(help="Show the live database schema.", no_args_is_help=True)
app.add_typer(create_app, name="create")
app.add_typer(apply_app, name="apply")
app.add_typer(check_app, name="check")
app.add_typer(teardown_app, name="teardown")
app.add_typer(show_app, name="show")

_APPLY_ORDER = ["tables", "roles", "users", "functions", "grants", "postgrest", "access-filter"]
_TEARDOWN_ORDER = ["access-filter", "postgrest", "functions", "tables", "roles", "users"]


def _write(domain: str, source: Path, sql: str) -> None:
    path = config.sql_file(domain)
    path.parent.mkdir(parents=True, exist_ok=True)
    header = f"-- generated by pgprovision create {domain} from {source}\n"
    statements = len([s for s in sql.strip().split(";") if s.strip()]) if sql.strip() else 0
    path.write_text(header + sql)
    typer.echo(f"wrote {path} ({statements} statements)")


@create_app.command("schemas")
def create_schemas() -> None:
    """Generate SQL for all domains (tables, roles, users, functions, grants, postgrest, access-filter)."""
    create_tables()
    create_roles()
    create_users()
    create_functions()
    create_grants()
    create_postgrest()
    create_access_filter()


@create_app.command("tables")
def create_tables() -> None:
    """Generate CREATE TABLE statements from tables.yaml."""
    _write("tables", config.tables_file(), sqlgen.tables(models.load_tables()))


@create_app.command("users")
def create_users() -> None:
    """Generate CREATE ROLE ... LOGIN statements from users.yaml."""
    _write("users", config.users_file(), sqlgen.users(models.load_users()))


@create_app.command("roles")
def create_roles() -> None:
    """Generate CREATE ROLE ... NOLOGIN statements from roles.yaml."""
    _write("roles", config.roles_file(), sqlgen.roles(models.load_roles()))


@create_app.command("grants")
def create_grants() -> None:
    """Generate GRANT statements from grants.yaml."""
    _write("grants", config.grants_file(), sqlgen.grants(models.load_grants()))


@create_app.command("functions")
def create_functions() -> None:
    """Generate CREATE FUNCTION statements from functions.yaml."""
    _write("functions", config.functions_file(), sqlgen.functions(models.load_functions()))


@create_app.command("postgrest")
def create_postgrest() -> None:
    """Generate ALTER ROLE ... SET pgrst.* statements from postgrest.yaml."""
    _write("postgrest", config.postgrest_file(), sqlgen.postgrest_config(models.load_postgrest()))


@create_app.command("access-filter")
def create_access_filter() -> None:
    """Generate the pgrmapper access_filter table + rows from access_filter.yaml."""
    _write("access-filter", config.access_filter_file(), sqlgen.access_filter(models.load_access_filter()))


def _apply(domain: str) -> None:
    path = config.sql_file(domain)
    if not path.exists():
        typer.echo(f"error: {path} not found (run 'pgprovision create {domain}' first)", err=True)
        raise typer.Exit(code=1)
    typer.echo(f"applying {path}")
    try:
        db.execute_file(path)
    except psycopg.Error as ex:
        typer.echo(f"error applying {path}: {ex}", err=True)
        typer.echo(
            "hint: the generated SQL uses plain CREATE/GRANT statements, so "
            "objects that already exist fail on re-apply. Run "
            "'pgprovision teardown schemas' first, or re-provision for a "
            "fresh database (scripts/provision.sh).",
            err=True,
        )
        raise typer.Exit(code=1)
    typer.echo(f"applied {path}")


def _maybe_reload() -> None:
    if config.autoreload_schemas():
        db.notify_reload_schema()
        db.notify_reload_config()
        typer.echo("sent schema cache + config reload (PGPROVISION_AUTORELOAD_SCHEMAS=true)")


@apply_app.command("schemas")
def apply_schemas() -> None:
    """Apply all generated SQL files in order (tables, roles, users, grants)."""
    for domain in _APPLY_ORDER:
        _apply(domain)
    _maybe_reload()


@apply_app.command("tables")
def apply_tables() -> None:
    """Apply tables.sql."""
    _apply("tables")
    _maybe_reload()


@apply_app.command("users")
def apply_users() -> None:
    """Apply users.sql."""
    _apply("users")
    _maybe_reload()


@apply_app.command("roles")
def apply_roles() -> None:
    """Apply roles.sql."""
    _apply("roles")
    _maybe_reload()


@apply_app.command("grants")
def apply_grants() -> None:
    """Apply grants.sql."""
    _apply("grants")
    _maybe_reload()


@apply_app.command("functions")
def apply_functions() -> None:
    """Apply functions.sql."""
    _apply("functions")
    _maybe_reload()


@apply_app.command("postgrest")
def apply_postgrest() -> None:
    """Apply postgrest.sql (in-database PostgREST settings)."""
    _apply("postgrest")
    _maybe_reload()


@apply_app.command("access-filter")
def apply_access_filter() -> None:
    """Apply access-filter.sql (replaces the pgrmapper access_filter ruleset)."""
    _apply("access-filter")
    _maybe_reload()


@app.command("reload-schema")
def reload_schema() -> None:
    """Tell PostgREST to rebuild its schema cache (NOTIFY pgrst, 'reload schema')."""
    db.notify_reload_schema()
    typer.echo("schema cache reload requested")


@app.command("reload-config")
def reload_config() -> None:
    """Tell PostgREST to apply in-database configuration (NOTIFY pgrst, 'reload config')."""
    db.notify_reload_config()
    typer.echo("config reload requested")


@check_app.command("schemas")
def check_schemas() -> None:
    """Verify tables, users, roles and grants match the live database."""
    raise typer.Exit(code=0 if checker.check_schemas() else 1)


@check_app.command("schema")
def check_schema(table_name: str) -> None:
    """Verify a single table matches the live database."""
    raise typer.Exit(code=0 if checker.check_table(table_name) else 1)


_TEARDOWN_BUILDERS = {
    "access-filter": lambda: sqlgen.drop_access_filter(),
    "postgrest": lambda: sqlgen.reset_postgrest_config(models.load_postgrest()),
    "functions": lambda: sqlgen.drop_functions(models.load_functions()),
    "tables": lambda: sqlgen.drop_tables(models.load_tables()),
    "roles": lambda: sqlgen.drop_roles(models.load_roles()),
    "users": lambda: sqlgen.drop_users(models.load_users()),
}


def _teardown(domain: str) -> None:
    sql = _TEARDOWN_BUILDERS[domain]()
    if not sql.strip():
        typer.echo(f"nothing to teardown for {domain}")
        return
    typer.echo(f"tearing down {domain}")
    try:
        db.execute_sql(sql)
    except psycopg.Error as ex:
        typer.echo(f"error tearing down {domain}: {ex}", err=True)
        raise typer.Exit(code=1)
    typer.echo(f"torn down {domain}")


@teardown_app.command("schemas")
def teardown_schemas() -> None:
    """Drop everything defined in the yaml templates.

    Grants are removed automatically with their tables/roles. Idempotent:
    safe to run on an already-clean database.
    """
    for domain in _TEARDOWN_ORDER:
        _teardown(domain)


@teardown_app.command("postgrest")
def teardown_postgrest() -> None:
    """Reset the in-database PostgREST settings defined in postgrest.yaml."""
    _teardown("postgrest")


@teardown_app.command("access-filter")
def teardown_access_filter() -> None:
    """Drop the pgrmapper access_filter table."""
    _teardown("access-filter")


@teardown_app.command("functions")
def teardown_functions() -> None:
    """Drop the functions defined in functions.yaml."""
    _teardown("functions")


@teardown_app.command("tables")
def teardown_tables() -> None:
    """Drop the tables defined in tables.yaml (and their grants)."""
    _teardown("tables")


@teardown_app.command("users")
def teardown_users() -> None:
    """Drop the roles defined in users.yaml."""
    _teardown("users")


@teardown_app.command("roles")
def teardown_roles() -> None:
    """Drop the roles defined in roles.yaml."""
    _teardown("roles")


@show_app.command("schemas")
def show_schemas() -> None:
    """List the tables in the configured database schema."""
    show.render_schemas()


@show_app.command("schema")
def show_schema(table_name: str) -> None:
    """Show a table's columns, required fields and an example POST body."""
    show.render_table(table_name)


if __name__ == "__main__":
    app()
