-- generated by pgprovision create access-filter from data/provision/examples/todos/access_filter.yaml
CREATE SCHEMA IF NOT EXISTS pgrmapper;
CREATE TABLE IF NOT EXISTS pgrmapper.access_filter (
  role text NOT NULL,
  "table" text NOT NULL,
  visible_columns text[] NOT NULL,
  PRIMARY KEY (role, "table")
);
DELETE FROM pgrmapper.access_filter;
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('anon', 'todos', ARRAY['id', 'title']);
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('editor', 'todos', ARRAY['id', 'title', 'done', 'priority']);
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('manager', 'todos', ARRAY['id', 'title', 'done', 'priority', 'due_date', 'owner']);
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('viewer', 'todos', ARRAY['id', 'title']);
