-- generated by pgprovision create access-filter from data/provision/examples/roles_api/access_filter.yaml
CREATE SCHEMA IF NOT EXISTS pgrmapper;
CREATE TABLE IF NOT EXISTS pgrmapper.access_filter (
  role text NOT NULL,
  "table" text NOT NULL,
  visible_columns text[] NOT NULL,
  PRIMARY KEY (role, "table")
);
DELETE FROM pgrmapper.access_filter;
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('viewer', 'users', ARRAY['user_id', 'user_name']::text[]);
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('viewer', 'applications', ARRAY['application_id', 'application_name']::text[]);
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('viewer', 'roles', ARRAY['role_id', 'role_name']::text[]);
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('viewer', 'grants', ARRAY[]::text[]);
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('editor', 'users', ARRAY['user_id', 'user_name', 'user_email']::text[]);
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('editor', 'applications', ARRAY['application_id', 'application_name', 'description']::text[]);
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('editor', 'roles', ARRAY['role_id', 'role_name', 'description']::text[]);
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('editor', 'grants', ARRAY['grant_id', 'user_id', 'application_id', 'role_id', 'granted_at']::text[]);
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('manager', 'users', ARRAY['user_id', 'user_name', 'user_email', 'status']::text[]);
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('manager', 'applications', ARRAY['application_id', 'application_name', 'description', 'owner_team']::text[]);
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('manager', 'roles', ARRAY['role_id', 'role_name', 'description']::text[]);
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('manager', 'grants', ARRAY['grant_id', 'user_id', 'application_id', 'role_id', 'granted_by', 'granted_at']::text[]);
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('administrator', 'users', ARRAY['user_id', 'user_name', 'user_email', 'status']::text[]);
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('administrator', 'applications', ARRAY['application_id', 'application_name', 'description', 'owner_team']::text[]);
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('administrator', 'roles', ARRAY['role_id', 'role_name', 'description']::text[]);
INSERT INTO pgrmapper.access_filter (role, "table", visible_columns) VALUES ('administrator', 'grants', ARRAY['grant_id', 'user_id', 'application_id', 'role_id', 'granted_by', 'granted_at']::text[]);
