-- generated by pgprovision create functions from data/provision/examples/todos/functions.yaml
CREATE SCHEMA IF NOT EXISTS auth;
GRANT USAGE ON SCHEMA auth TO PUBLIC;
CREATE OR REPLACE FUNCTION auth.check_token() RETURNS void LANGUAGE plpgsql AS $$ begin
  if current_setting('request.headers', true)::json->>'x-block' = 'yes' then
    raise insufficient_privilege using hint = 'blocked by pre-request';
  end if;
end
 $$;
