-- generated by pgprovision create grants from data/provision/examples/todos/grants.yaml
GRANT SELECT ON TABLE todos TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE todos TO editor;
GRANT SELECT ON TABLE todos TO manager;
GRANT SELECT ON TABLE todos TO viewer;
GRANT SELECT ON TABLE todos TO test_anon;
