-- generated by pgprovision create roles from data/provision/examples/todos/roles.yaml
CREATE ROLE test_anon NOLOGIN;
CREATE ROLE editor NOLOGIN;
GRANT editor TO authenticator;
CREATE ROLE manager NOLOGIN;
GRANT manager TO authenticator;
CREATE ROLE viewer NOLOGIN;
GRANT viewer TO authenticator;
