-- generated by pgprovision create roles from data/provision/examples/roles_api/roles.yaml
CREATE ROLE editor NOLOGIN;
GRANT editor TO authenticator;
CREATE ROLE manager NOLOGIN;
GRANT manager TO authenticator;
CREATE ROLE viewer NOLOGIN;
GRANT viewer TO authenticator;
CREATE ROLE administrator NOLOGIN;
GRANT administrator TO authenticator;
