-- generated by pgprovision create tables from data/provision/examples/todos/tables.yaml
CREATE TABLE todos (
  id integer NOT NULL,
  title text NOT NULL,
  done boolean DEFAULT FALSE,
  priority text,
  due_date date,
  owner text,
  PRIMARY KEY (id)
);
