-- generated by pgprovision create tables from data/provision/examples/roles_api/tables.yaml
CREATE TABLE users (
  user_id integer NOT NULL,
  user_name text NOT NULL,
  user_email text NOT NULL,
  status text DEFAULT 'active',
  PRIMARY KEY (user_id)
);

CREATE TABLE applications (
  application_id integer NOT NULL,
  application_name text NOT NULL,
  description text,
  owner_team text,
  PRIMARY KEY (application_id)
);

CREATE TABLE roles (
  role_id integer NOT NULL,
  role_name text NOT NULL,
  description text,
  PRIMARY KEY (role_id)
);

CREATE TABLE grants (
  grant_id integer NOT NULL,
  user_id integer NOT NULL REFERENCES users (user_id),
  application_id integer NOT NULL REFERENCES applications (application_id),
  role_id integer NOT NULL REFERENCES roles (role_id),
  granted_by text,
  granted_at date,
  PRIMARY KEY (grant_id)
);
